### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by WidgetKing** [WidgetKing/advance-online-cp-utils#5]
One thing I forgot to ask, what browsers are you planning to deliver to. Basically, I need to know whether we have to support Internet Explorer. If that's the case then there will be added time setting up the code base to run through the Babel transpiler to ensure the code in compatible. The delivered file will also be larger as it will need to include polyfills for Internet Explorer.

**Comment by AdvanceOnlineHou** [comment]
No we have left IE behind.
We support Edge, Chrome, Safari, FF

**Comment by WidgetKing** [comment]
Thank goodness.
